ported over local code
nere1 was outdated test from my computer / didn't work well

diff --git a/nere1 b/nere1
--- a/nere1
+++ b/nere1
@@ -1,5 +1,4 @@
 #! /usr/bin/env sh
-
 description=null    # Optional Description flag 
 private=false       # Private defaulted to false
 delete=false        # Delete defaulted to false 
@@ -9,14 +8,14 @@ access_token=
 username=           # Void Username may move to global
 reponame=           # Void reponame
 show=               # option to show other users
-pat=                # Personal Access Token or Password may move to globle
+pat=                # Personal Access Token or Password may move to globle               
+
 
 # Color List
-NC='\x1b[0m' # Return Default
-RED='\x1b[38;5;9m' # Error
-BLUE='\x1b[0;34m' # feeling blue
-GREEN='\x1B[32m' # Success
-
+NC='\x1b[0m'        # Return Default
+RED='\x1b[38;5;9m'  # Error
+BLUE='\x1b[0;34m'   # feeling blue
+GREEN='\x1B[32m'    # Success
 
 function cleanUp()
 {
@@ -24,7 +23,7 @@ function cleanUp()
     exit 0
 }
 
-function usage() # Help and Usage case for the shell
+function usage()
 {
     echo "usage: nere [-h help] [-u username ]  ${RED}[${NC} [-p password] or [-a auth] ${RED}]${NC}  [-r reponame] [-d description] "
     exit 0
@@ -51,8 +50,7 @@ function main()
             exit 0
         fi        
     else 
-        curl -s -H "Authorization: token $access_token" https://api.github.com/user/repos -d "{\"name\":\"$reponame\", \"description\":$description, \"private\":$private}" | grep --s "Bad credentials" && echo "${RED}Error: Bad Credentials${NC}" && exit 0
-        echo "$username:$pat"
+        curl -s -u $username https://api.github.com/user/repos -d "{\"name\":\"$reponame\", \"description\":$description, \"private\":$private}" | grep --s "Bad credentials" && echo "${RED}Error: Bad Credentials${NC}" && exit 0
         # remove ! for testing purpose
         if  ! [ -x "$(command -v git)" ]; then
             echo "${GREEN}Sucess: Online Repository made to: ${NC}$username"
@@ -94,7 +92,7 @@ trap cleanUp 2 # Aborts Program
 
 while [ "$1" != "" ]; do
     case $1 in
-        --help | -h )           shift
+        help )                  shift
                                 usage
                                 ;;
         --list )                shift
@@ -129,21 +127,17 @@ while [ "$1" != "" ]; do
     shift
 done
 
+if ! [ -z $pat ]; then
+    username="$username:$pat"
+fi
 
-# Checks if $username has been assign a string yet
+# Checks if variables have been assigned a value
 while [ -z $username ] || [ "$username" = "" ] || [[ $username = *[![:ascii:]]* ]]; do
         read -p "[Username]: " username
     done
 
-# Checks if $access_token has been assign a string yet
-while [ -z $access_token ] || [ "$access_token" = "" ] || [[ $access_token = *[![:ascii:]]* ]]; do
-        read -p "[Reponame]: " access_token 
-    done
-
-# Checks if $reponame has been assign a string yet
 while [ -z $reponame ] || [ "$reponame" = "" ] || [[ $reponame = *[![:ascii:]]* ]]; do
         read -p "[Reponame]: " reponame 
     done
-
 
 main
